CREATE TABLE EmailMessage
(
	Email_ID SERIAL NOT NULL,
	Creation_Time TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
	Origin CHARACTER VARYING(255),
	Destination TEXT,
	Inbound BOOLEAN NOT NULL,
	Outbound BOOLEAN NOT NULL,
	Response BOOLEAN,
	Message_UID TEXT,
	Subject TEXT,
	Body TEXT,
	Application_Generated BOOLEAN,
	Application_ID INTEGER,
	Reference_ID INTEGER,
	Reference_Type INTEGER,
	Sent BOOLEAN,
	Sent_Time TIMESTAMP WITH TIME ZONE,
	Processed BOOLEAN,
	Processed_Time TIMESTAMP WITH TIME ZONE,
	Error BOOLEAN,
	Error_Message TEXT,
	CONSTRAINT Email_ID_PKEY PRIMARY KEY (Email_ID)
)
WITH (
	OIDS=FALSE
);
ALTER TABLE EmailMessage
	OWNER TO "PSMaintStaging";
COMMENT ON TABLE EmailMessage 
	IS 'This table will represent any and all messages that are encountered in our mailbox. This table will need columns that lets us qualify the message, whether generated by us, whether it is a response. Special note about this table sit hat the column reference ID will act as forigen keys or self referencing keys depending on the value';
