//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProudSourcePrime.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentFileComposite", Namespace="http://schemas.datacontract.org/2004/07/ProudSourceWCFService")]
    [System.SerializableAttribute()]
    public partial class DocumentFileComposite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, object> DocumentDictField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object> DocumentDict {
            get {
                return this.DocumentDictField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentDictField, value) != true)) {
                    this.DocumentDictField = value;
                    this.RaisePropertyChanged("DocumentDict");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageFileComposite", Namespace="http://schemas.datacontract.org/2004/07/ProudSourceWCFService")]
    [System.SerializableAttribute()]
    public partial class ImageFileComposite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, object> ImageDictField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object> ImageDict {
            get {
                return this.ImageDictField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageDictField, value) != true)) {
                    this.ImageDictField = value;
                    this.RaisePropertyChanged("ImageDict");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRecordComposite", Namespace="http://schemas.datacontract.org/2004/07/ProudSourceWCFService")]
    [System.SerializableAttribute()]
    public partial class UserRecordComposite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccessFailedCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EmailConfirmedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LockoutEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LockoutEndDateUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PhoneNumberConfirmedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TwoFactorEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccessFailedCount {
            get {
                return this.AccessFailedCountField;
            }
            set {
                if ((this.AccessFailedCountField.Equals(value) != true)) {
                    this.AccessFailedCountField = value;
                    this.RaisePropertyChanged("AccessFailedCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EmailConfirmed {
            get {
                return this.EmailConfirmedField;
            }
            set {
                if ((this.EmailConfirmedField.Equals(value) != true)) {
                    this.EmailConfirmedField = value;
                    this.RaisePropertyChanged("EmailConfirmed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LockoutEnabled {
            get {
                return this.LockoutEnabledField;
            }
            set {
                if ((this.LockoutEnabledField.Equals(value) != true)) {
                    this.LockoutEnabledField = value;
                    this.RaisePropertyChanged("LockoutEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LockoutEndDateUtc {
            get {
                return this.LockoutEndDateUtcField;
            }
            set {
                if ((this.LockoutEndDateUtcField.Equals(value) != true)) {
                    this.LockoutEndDateUtcField = value;
                    this.RaisePropertyChanged("LockoutEndDateUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash {
            get {
                return this.PasswordHashField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordHashField, value) != true)) {
                    this.PasswordHashField = value;
                    this.RaisePropertyChanged("PasswordHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PhoneNumberConfirmed {
            get {
                return this.PhoneNumberConfirmedField;
            }
            set {
                if ((this.PhoneNumberConfirmedField.Equals(value) != true)) {
                    this.PhoneNumberConfirmedField = value;
                    this.RaisePropertyChanged("PhoneNumberConfirmed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityStamp {
            get {
                return this.SecurityStampField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityStampField, value) != true)) {
                    this.SecurityStampField = value;
                    this.RaisePropertyChanged("SecurityStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TwoFactorEnabled {
            get {
                return this.TwoFactorEnabledField;
            }
            set {
                if ((this.TwoFactorEnabledField.Equals(value) != true)) {
                    this.TwoFactorEnabledField = value;
                    this.RaisePropertyChanged("TwoFactorEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserIndexComposite", Namespace="http://schemas.datacontract.org/2004/07/ProudSourceWCFService")]
    [System.SerializableAttribute()]
    public partial class UserIndexComposite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurAccountsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurDocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurEmbelishmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurLinksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> EntrepreneurProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> InvestorAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> InvestorDocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> InvestorEmbelishmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> InvestorLinksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> InvestorProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Investor_Financial_Account_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> UserProfileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurAccounts {
            get {
                return this.EntrepreneurAccountsField;
            }
            set {
                if ((object.ReferenceEquals(this.EntrepreneurAccountsField, value) != true)) {
                    this.EntrepreneurAccountsField = value;
                    this.RaisePropertyChanged("EntrepreneurAccounts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurDocuments {
            get {
                return this.EntrepreneurDocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.EntrepreneurDocumentsField, value) != true)) {
                    this.EntrepreneurDocumentsField = value;
                    this.RaisePropertyChanged("EntrepreneurDocuments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurEmbelishments {
            get {
                return this.EntrepreneurEmbelishmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.EntrepreneurEmbelishmentsField, value) != true)) {
                    this.EntrepreneurEmbelishmentsField = value;
                    this.RaisePropertyChanged("EntrepreneurEmbelishments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurLinks {
            get {
                return this.EntrepreneurLinksField;
            }
            set {
                if ((object.ReferenceEquals(this.EntrepreneurLinksField, value) != true)) {
                    this.EntrepreneurLinksField = value;
                    this.RaisePropertyChanged("EntrepreneurLinks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> EntrepreneurProfile {
            get {
                return this.EntrepreneurProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.EntrepreneurProfileField, value) != true)) {
                    this.EntrepreneurProfileField = value;
                    this.RaisePropertyChanged("EntrepreneurProfile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> InvestorAccount {
            get {
                return this.InvestorAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.InvestorAccountField, value) != true)) {
                    this.InvestorAccountField = value;
                    this.RaisePropertyChanged("InvestorAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> InvestorDocuments {
            get {
                return this.InvestorDocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.InvestorDocumentsField, value) != true)) {
                    this.InvestorDocumentsField = value;
                    this.RaisePropertyChanged("InvestorDocuments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> InvestorEmbelishments {
            get {
                return this.InvestorEmbelishmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.InvestorEmbelishmentsField, value) != true)) {
                    this.InvestorEmbelishmentsField = value;
                    this.RaisePropertyChanged("InvestorEmbelishments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> InvestorLinks {
            get {
                return this.InvestorLinksField;
            }
            set {
                if ((object.ReferenceEquals(this.InvestorLinksField, value) != true)) {
                    this.InvestorLinksField = value;
                    this.RaisePropertyChanged("InvestorLinks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> InvestorProfile {
            get {
                return this.InvestorProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.InvestorProfileField, value) != true)) {
                    this.InvestorProfileField = value;
                    this.RaisePropertyChanged("InvestorProfile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Investor_Financial_Account_Id {
            get {
                return this.Investor_Financial_Account_IdField;
            }
            set {
                if ((this.Investor_Financial_Account_IdField.Equals(value) != true)) {
                    this.Investor_Financial_Account_IdField = value;
                    this.RaisePropertyChanged("Investor_Financial_Account_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> UserProfile {
            get {
                return this.UserProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.UserProfileField, value) != true)) {
                    this.UserProfileField = value;
                    this.RaisePropertyChanged("UserProfile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvestorIndexComposite", Namespace="http://schemas.datacontract.org/2004/07/ProudSourceWCFService")]
    [System.SerializableAttribute()]
    public partial class InvestorIndexComposite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> InvestorAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvestorAccount_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> InvestorDocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> InvestorEmbelishmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> InvestorLinksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> InvestorProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> InvestorePROCsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> InvestorAccount {
            get {
                return this.InvestorAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.InvestorAccountField, value) != true)) {
                    this.InvestorAccountField = value;
                    this.RaisePropertyChanged("InvestorAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvestorAccount_Id {
            get {
                return this.InvestorAccount_IdField;
            }
            set {
                if ((this.InvestorAccount_IdField.Equals(value) != true)) {
                    this.InvestorAccount_IdField = value;
                    this.RaisePropertyChanged("InvestorAccount_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> InvestorDocuments {
            get {
                return this.InvestorDocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.InvestorDocumentsField, value) != true)) {
                    this.InvestorDocumentsField = value;
                    this.RaisePropertyChanged("InvestorDocuments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> InvestorEmbelishments {
            get {
                return this.InvestorEmbelishmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.InvestorEmbelishmentsField, value) != true)) {
                    this.InvestorEmbelishmentsField = value;
                    this.RaisePropertyChanged("InvestorEmbelishments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> InvestorLinks {
            get {
                return this.InvestorLinksField;
            }
            set {
                if ((object.ReferenceEquals(this.InvestorLinksField, value) != true)) {
                    this.InvestorLinksField = value;
                    this.RaisePropertyChanged("InvestorLinks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> InvestorProfile {
            get {
                return this.InvestorProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.InvestorProfileField, value) != true)) {
                    this.InvestorProfileField = value;
                    this.RaisePropertyChanged("InvestorProfile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> InvestorePROCs {
            get {
                return this.InvestorePROCsField;
            }
            set {
                if ((object.ReferenceEquals(this.InvestorePROCsField, value) != true)) {
                    this.InvestorePROCsField = value;
                    this.RaisePropertyChanged("InvestorePROCs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvestorDetailsComposite", Namespace="http://schemas.datacontract.org/2004/07/ProudSourceWCFService")]
    [System.SerializableAttribute()]
    public partial class InvestorDetailsComposite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> InvestorDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> InvestorDocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> InvestorEmbelishmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> InvestorLinksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> InvestorPROCsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> InvestorDetails {
            get {
                return this.InvestorDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.InvestorDetailsField, value) != true)) {
                    this.InvestorDetailsField = value;
                    this.RaisePropertyChanged("InvestorDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> InvestorDocuments {
            get {
                return this.InvestorDocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.InvestorDocumentsField, value) != true)) {
                    this.InvestorDocumentsField = value;
                    this.RaisePropertyChanged("InvestorDocuments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> InvestorEmbelishments {
            get {
                return this.InvestorEmbelishmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.InvestorEmbelishmentsField, value) != true)) {
                    this.InvestorEmbelishmentsField = value;
                    this.RaisePropertyChanged("InvestorEmbelishments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> InvestorLinks {
            get {
                return this.InvestorLinksField;
            }
            set {
                if ((object.ReferenceEquals(this.InvestorLinksField, value) != true)) {
                    this.InvestorLinksField = value;
                    this.RaisePropertyChanged("InvestorLinks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> InvestorPROCs {
            get {
                return this.InvestorPROCsField;
            }
            set {
                if ((object.ReferenceEquals(this.InvestorPROCsField, value) != true)) {
                    this.InvestorPROCsField = value;
                    this.RaisePropertyChanged("InvestorPROCs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntrepreneurIndexComposite", Namespace="http://schemas.datacontract.org/2004/07/ProudSourceWCFService")]
    [System.SerializableAttribute()]
    public partial class EntrepreneurIndexComposite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurDocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurEmbelishmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurLinksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> EntrepreneurProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurProjectsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurDocuments {
            get {
                return this.EntrepreneurDocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.EntrepreneurDocumentsField, value) != true)) {
                    this.EntrepreneurDocumentsField = value;
                    this.RaisePropertyChanged("EntrepreneurDocuments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurEmbelishments {
            get {
                return this.EntrepreneurEmbelishmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.EntrepreneurEmbelishmentsField, value) != true)) {
                    this.EntrepreneurEmbelishmentsField = value;
                    this.RaisePropertyChanged("EntrepreneurEmbelishments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurLinks {
            get {
                return this.EntrepreneurLinksField;
            }
            set {
                if ((object.ReferenceEquals(this.EntrepreneurLinksField, value) != true)) {
                    this.EntrepreneurLinksField = value;
                    this.RaisePropertyChanged("EntrepreneurLinks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> EntrepreneurProfile {
            get {
                return this.EntrepreneurProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.EntrepreneurProfileField, value) != true)) {
                    this.EntrepreneurProfileField = value;
                    this.RaisePropertyChanged("EntrepreneurProfile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurProjects {
            get {
                return this.EntrepreneurProjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.EntrepreneurProjectsField, value) != true)) {
                    this.EntrepreneurProjectsField = value;
                    this.RaisePropertyChanged("EntrepreneurProjects");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntrepreneurDetailsComposite", Namespace="http://schemas.datacontract.org/2004/07/ProudSourceWCFService")]
    [System.SerializableAttribute()]
    public partial class EntrepreneurDetailsComposite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> EntrepreneurDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurDocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurEmbelishmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurLinksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurPROCSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurProjectsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> EntrepreneurDetails {
            get {
                return this.EntrepreneurDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.EntrepreneurDetailsField, value) != true)) {
                    this.EntrepreneurDetailsField = value;
                    this.RaisePropertyChanged("EntrepreneurDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurDocuments {
            get {
                return this.EntrepreneurDocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.EntrepreneurDocumentsField, value) != true)) {
                    this.EntrepreneurDocumentsField = value;
                    this.RaisePropertyChanged("EntrepreneurDocuments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurEmbelishments {
            get {
                return this.EntrepreneurEmbelishmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.EntrepreneurEmbelishmentsField, value) != true)) {
                    this.EntrepreneurEmbelishmentsField = value;
                    this.RaisePropertyChanged("EntrepreneurEmbelishments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurLinks {
            get {
                return this.EntrepreneurLinksField;
            }
            set {
                if ((object.ReferenceEquals(this.EntrepreneurLinksField, value) != true)) {
                    this.EntrepreneurLinksField = value;
                    this.RaisePropertyChanged("EntrepreneurLinks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurPROCS {
            get {
                return this.EntrepreneurPROCSField;
            }
            set {
                if ((object.ReferenceEquals(this.EntrepreneurPROCSField, value) != true)) {
                    this.EntrepreneurPROCSField = value;
                    this.RaisePropertyChanged("EntrepreneurPROCS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> EntrepreneurProjects {
            get {
                return this.EntrepreneurProjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.EntrepreneurProjectsField, value) != true)) {
                    this.EntrepreneurProjectsField = value;
                    this.RaisePropertyChanged("EntrepreneurProjects");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectIndexComposite", Namespace="http://schemas.datacontract.org/2004/07/ProudSourceWCFService")]
    [System.SerializableAttribute()]
    public partial class ProjectIndexComposite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ProjectAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectAccount_IntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> ProjectDocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> ProjectEmbelishmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> ProjectImagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> ProjectLinksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> ProjectPROCsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ProjectProfileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ProjectAccount {
            get {
                return this.ProjectAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectAccountField, value) != true)) {
                    this.ProjectAccountField = value;
                    this.RaisePropertyChanged("ProjectAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectAccount_Int {
            get {
                return this.ProjectAccount_IntField;
            }
            set {
                if ((this.ProjectAccount_IntField.Equals(value) != true)) {
                    this.ProjectAccount_IntField = value;
                    this.RaisePropertyChanged("ProjectAccount_Int");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> ProjectDocuments {
            get {
                return this.ProjectDocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectDocumentsField, value) != true)) {
                    this.ProjectDocumentsField = value;
                    this.RaisePropertyChanged("ProjectDocuments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> ProjectEmbelishments {
            get {
                return this.ProjectEmbelishmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectEmbelishmentsField, value) != true)) {
                    this.ProjectEmbelishmentsField = value;
                    this.RaisePropertyChanged("ProjectEmbelishments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> ProjectImages {
            get {
                return this.ProjectImagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectImagesField, value) != true)) {
                    this.ProjectImagesField = value;
                    this.RaisePropertyChanged("ProjectImages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> ProjectLinks {
            get {
                return this.ProjectLinksField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectLinksField, value) != true)) {
                    this.ProjectLinksField = value;
                    this.RaisePropertyChanged("ProjectLinks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> ProjectPROCs {
            get {
                return this.ProjectPROCsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectPROCsField, value) != true)) {
                    this.ProjectPROCsField = value;
                    this.RaisePropertyChanged("ProjectPROCs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ProjectProfile {
            get {
                return this.ProjectProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectProfileField, value) != true)) {
                    this.ProjectProfileField = value;
                    this.RaisePropertyChanged("ProjectProfile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectDetailsComposite", Namespace="http://schemas.datacontract.org/2004/07/ProudSourceWCFService")]
    [System.SerializableAttribute()]
    public partial class ProjectDetailsComposite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ProjectDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> ProjectDocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> ProjectEmbelishmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> ProjectImagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> ProjectLinksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> ProjectPROCsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ProjectDetails {
            get {
                return this.ProjectDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectDetailsField, value) != true)) {
                    this.ProjectDetailsField = value;
                    this.RaisePropertyChanged("ProjectDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> ProjectDocuments {
            get {
                return this.ProjectDocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectDocumentsField, value) != true)) {
                    this.ProjectDocumentsField = value;
                    this.RaisePropertyChanged("ProjectDocuments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> ProjectEmbelishments {
            get {
                return this.ProjectEmbelishmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectEmbelishmentsField, value) != true)) {
                    this.ProjectEmbelishmentsField = value;
                    this.RaisePropertyChanged("ProjectEmbelishments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> ProjectImages {
            get {
                return this.ProjectImagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectImagesField, value) != true)) {
                    this.ProjectImagesField = value;
                    this.RaisePropertyChanged("ProjectImages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> ProjectLinks {
            get {
                return this.ProjectLinksField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectLinksField, value) != true)) {
                    this.ProjectLinksField = value;
                    this.RaisePropertyChanged("ProjectLinks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> ProjectPROCs {
            get {
                return this.ProjectPROCsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectPROCsField, value) != true)) {
                    this.ProjectPROCsField = value;
                    this.RaisePropertyChanged("ProjectPROCs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PROCComposite", Namespace="http://schemas.datacontract.org/2004/07/ProudSourceWCFService")]
    [System.SerializableAttribute()]
    public partial class PROCComposite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EntrepreneurOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InvestorOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> PROCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EntrepreneurOwner {
            get {
                return this.EntrepreneurOwnerField;
            }
            set {
                if ((this.EntrepreneurOwnerField.Equals(value) != true)) {
                    this.EntrepreneurOwnerField = value;
                    this.RaisePropertyChanged("EntrepreneurOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InvestorOwner {
            get {
                return this.InvestorOwnerField;
            }
            set {
                if ((this.InvestorOwnerField.Equals(value) != true)) {
                    this.InvestorOwnerField = value;
                    this.RaisePropertyChanged("InvestorOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PROC {
            get {
                return this.PROCField;
            }
            set {
                if ((object.ReferenceEquals(this.PROCField, value) != true)) {
                    this.PROCField = value;
                    this.RaisePropertyChanged("PROC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinancialAccountComposite", Namespace="http://schemas.datacontract.org/2004/07/ProudSourceWCFService")]
    [System.SerializableAttribute()]
    public partial class FinancialAccountComposite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Client_Braintree_TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> FinancialAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> FinancialTransactions_FailedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> FinancialTransactions_PendingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> FinancialTransactions_ProcessedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Client_Braintree_Token {
            get {
                return this.Client_Braintree_TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.Client_Braintree_TokenField, value) != true)) {
                    this.Client_Braintree_TokenField = value;
                    this.RaisePropertyChanged("Client_Braintree_Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> FinancialAccount {
            get {
                return this.FinancialAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.FinancialAccountField, value) != true)) {
                    this.FinancialAccountField = value;
                    this.RaisePropertyChanged("FinancialAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> FinancialTransactions_Failed {
            get {
                return this.FinancialTransactions_FailedField;
            }
            set {
                if ((object.ReferenceEquals(this.FinancialTransactions_FailedField, value) != true)) {
                    this.FinancialTransactions_FailedField = value;
                    this.RaisePropertyChanged("FinancialTransactions_Failed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> FinancialTransactions_Pending {
            get {
                return this.FinancialTransactions_PendingField;
            }
            set {
                if ((object.ReferenceEquals(this.FinancialTransactions_PendingField, value) != true)) {
                    this.FinancialTransactions_PendingField = value;
                    this.RaisePropertyChanged("FinancialTransactions_Pending");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.Dictionary<string, string>> FinancialTransactions_Processed {
            get {
                return this.FinancialTransactions_ProcessedField;
            }
            set {
                if ((object.ReferenceEquals(this.FinancialTransactions_ProcessedField, value) != true)) {
                    this.FinancialTransactions_ProcessedField = value;
                    this.RaisePropertyChanged("FinancialTransactions_Processed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/upload_Document", ReplyAction="http://tempuri.org/IService1/upload_DocumentResponse")]
        bool upload_Document(ProudSourcePrime.ServiceReference1.DocumentFileComposite document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_Document", ReplyAction="http://tempuri.org/IService1/update_DocumentResponse")]
        bool update_Document(ProudSourcePrime.ServiceReference1.DocumentFileComposite document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete_Document", ReplyAction="http://tempuri.org/IService1/delete_DocumentResponse")]
        bool delete_Document(int document_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_Document", ReplyAction="http://tempuri.org/IService1/get_DocumentResponse")]
        System.Collections.Generic.Dictionary<string, string> get_Document(int document_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/upload_Image", ReplyAction="http://tempuri.org/IService1/upload_ImageResponse")]
        bool upload_Image(ProudSourcePrime.ServiceReference1.ImageFileComposite image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_Image", ReplyAction="http://tempuri.org/IService1/update_ImageResponse")]
        bool update_Image(ProudSourcePrime.ServiceReference1.ImageFileComposite image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete_Image", ReplyAction="http://tempuri.org/IService1/delete_ImageResponse")]
        bool delete_Image(int image_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_Image", ReplyAction="http://tempuri.org/IService1/get_ImageResponse")]
        string get_Image(int image_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_UserById", ReplyAction="http://tempuri.org/IService1/get_UserByIdResponse")]
        ProudSourcePrime.ServiceReference1.UserRecordComposite get_UserById(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_UserByUserName", ReplyAction="http://tempuri.org/IService1/get_UserByUserNameResponse")]
        ProudSourcePrime.ServiceReference1.UserRecordComposite get_UserByUserName(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_PasswordHash", ReplyAction="http://tempuri.org/IService1/get_PasswordHashResponse")]
        string get_PasswordHash(string UserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/set_PasswordHash", ReplyAction="http://tempuri.org/IService1/set_PasswordHashResponse")]
        bool set_PasswordHash(string userId, string passwordHash, string userName, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_UserIndexData", ReplyAction="http://tempuri.org/IService1/get_UserIndexDataResponse")]
        ProudSourcePrime.ServiceReference1.UserIndexComposite get_UserIndexData(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_ProfileData", ReplyAction="http://tempuri.org/IService1/update_ProfileDataResponse")]
        bool update_ProfileData(string UserId, System.Collections.Generic.Dictionary<string, string> userdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_InvestorIndexData", ReplyAction="http://tempuri.org/IService1/get_InvestorIndexDataResponse")]
        ProudSourcePrime.ServiceReference1.InvestorIndexComposite get_InvestorIndexData(string UserId, int investor_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_InvestorDetails_Data", ReplyAction="http://tempuri.org/IService1/get_InvestorDetails_DataResponse")]
        ProudSourcePrime.ServiceReference1.InvestorDetailsComposite get_InvestorDetails_Data(int Investor_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_EntrepreneurIndexData", ReplyAction="http://tempuri.org/IService1/get_EntrepreneurIndexDataResponse")]
        ProudSourcePrime.ServiceReference1.EntrepreneurIndexComposite get_EntrepreneurIndexData(string UserId, int entrepreneur_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_EntrepreneurDetails_Data", ReplyAction="http://tempuri.org/IService1/get_EntrepreneurDetails_DataResponse")]
        ProudSourcePrime.ServiceReference1.EntrepreneurDetailsComposite get_EntrepreneurDetails_Data(int Entrepreneur_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/create_Project", ReplyAction="http://tempuri.org/IService1/create_ProjectResponse")]
        int create_Project(string UserId, int Entrepreneur_Id, System.Collections.Generic.Dictionary<string, string> projectdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_ProjectIndexData", ReplyAction="http://tempuri.org/IService1/get_ProjectIndexDataResponse")]
        ProudSourcePrime.ServiceReference1.ProjectIndexComposite get_ProjectIndexData(string UserId, int entrepreneur_id, int project_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_ProjectDetails_Data", ReplyAction="http://tempuri.org/IService1/get_ProjectDetails_DataResponse")]
        ProudSourcePrime.ServiceReference1.ProjectDetailsComposite get_ProjectDetails_Data(int Project_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_ProjectProfileData", ReplyAction="http://tempuri.org/IService1/update_ProjectProfileDataResponse")]
        bool update_ProjectProfileData(string UserId, int Entrepreneur_Id, int Project_Id, System.Collections.Generic.Dictionary<string, string> projectdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/create_PROC", ReplyAction="http://tempuri.org/IService1/create_PROCResponse")]
        int create_PROC(string UserId, int Investor_Id, int Project_Id, System.Collections.Generic.Dictionary<string, string> PROCdata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_PROC", ReplyAction="http://tempuri.org/IService1/get_PROCResponse")]
        ProudSourcePrime.ServiceReference1.PROCComposite get_PROC(int proc_id, int entrepreneur_id, int investor_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_PROC", ReplyAction="http://tempuri.org/IService1/update_PROCResponse")]
        bool update_PROC(int proc_id, System.Collections.Generic.Dictionary<string, string> updateDictionary, int entrepreneur_id, int investor_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/alter_PROC_MutualyAccepted", ReplyAction="http://tempuri.org/IService1/alter_PROC_MutualyAcceptedResponse")]
        bool alter_PROC_MutualyAccepted(int proc_id, bool investor_mutualy_accepts_PROC, int entrepreneur_id, int investor_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/recant_PROC_MutualAcceptance", ReplyAction="http://tempuri.org/IService1/recant_PROC_MutualAcceptanceResponse")]
        bool recant_PROC_MutualAcceptance(int proc_id, bool mutual_acceptance, int entrepreneur_id, int investor_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/upload_Link", ReplyAction="http://tempuri.org/IService1/upload_LinkResponse")]
        bool upload_Link(System.Collections.Generic.Dictionary<string, string> link);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete_Link", ReplyAction="http://tempuri.org/IService1/delete_LinkResponse")]
        bool delete_Link(int link_id, int profile_id, int profile_type_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get_FinancialAccountData", ReplyAction="http://tempuri.org/IService1/get_FinancialAccountDataResponse")]
        ProudSourcePrime.ServiceReference1.FinancialAccountComposite get_FinancialAccountData(string UserId, int account_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/create_new_BT_Transactions", ReplyAction="http://tempuri.org/IService1/create_new_BT_TransactionsResponse")]
        bool create_new_BT_Transactions(string UserId, int account_Id, string nonce, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ajax_SearchResults", ReplyAction="http://tempuri.org/IService1/ajax_SearchResultsResponse")]
        System.Collections.Generic.Dictionary<string, string>[] ajax_SearchResults(string keyArg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ProudSourcePrime.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ProudSourcePrime.ServiceReference1.IService1>, ProudSourcePrime.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool upload_Document(ProudSourcePrime.ServiceReference1.DocumentFileComposite document) {
            return base.Channel.upload_Document(document);
        }
        
        public bool update_Document(ProudSourcePrime.ServiceReference1.DocumentFileComposite document) {
            return base.Channel.update_Document(document);
        }
        
        public bool delete_Document(int document_id) {
            return base.Channel.delete_Document(document_id);
        }
        
        public System.Collections.Generic.Dictionary<string, string> get_Document(int document_Id) {
            return base.Channel.get_Document(document_Id);
        }
        
        public bool upload_Image(ProudSourcePrime.ServiceReference1.ImageFileComposite image) {
            return base.Channel.upload_Image(image);
        }
        
        public bool update_Image(ProudSourcePrime.ServiceReference1.ImageFileComposite image) {
            return base.Channel.update_Image(image);
        }
        
        public bool delete_Image(int image_id) {
            return base.Channel.delete_Image(image_id);
        }
        
        public string get_Image(int image_id) {
            return base.Channel.get_Image(image_id);
        }
        
        public ProudSourcePrime.ServiceReference1.UserRecordComposite get_UserById(string Id) {
            return base.Channel.get_UserById(Id);
        }
        
        public ProudSourcePrime.ServiceReference1.UserRecordComposite get_UserByUserName(string UserName) {
            return base.Channel.get_UserByUserName(UserName);
        }
        
        public string get_PasswordHash(string UserId) {
            return base.Channel.get_PasswordHash(UserId);
        }
        
        public bool set_PasswordHash(string userId, string passwordHash, string userName, string name) {
            return base.Channel.set_PasswordHash(userId, passwordHash, userName, name);
        }
        
        public ProudSourcePrime.ServiceReference1.UserIndexComposite get_UserIndexData(string userId) {
            return base.Channel.get_UserIndexData(userId);
        }
        
        public bool update_ProfileData(string UserId, System.Collections.Generic.Dictionary<string, string> userdata) {
            return base.Channel.update_ProfileData(UserId, userdata);
        }
        
        public ProudSourcePrime.ServiceReference1.InvestorIndexComposite get_InvestorIndexData(string UserId, int investor_id) {
            return base.Channel.get_InvestorIndexData(UserId, investor_id);
        }
        
        public ProudSourcePrime.ServiceReference1.InvestorDetailsComposite get_InvestorDetails_Data(int Investor_Id) {
            return base.Channel.get_InvestorDetails_Data(Investor_Id);
        }
        
        public ProudSourcePrime.ServiceReference1.EntrepreneurIndexComposite get_EntrepreneurIndexData(string UserId, int entrepreneur_id) {
            return base.Channel.get_EntrepreneurIndexData(UserId, entrepreneur_id);
        }
        
        public ProudSourcePrime.ServiceReference1.EntrepreneurDetailsComposite get_EntrepreneurDetails_Data(int Entrepreneur_Id) {
            return base.Channel.get_EntrepreneurDetails_Data(Entrepreneur_Id);
        }
        
        public int create_Project(string UserId, int Entrepreneur_Id, System.Collections.Generic.Dictionary<string, string> projectdata) {
            return base.Channel.create_Project(UserId, Entrepreneur_Id, projectdata);
        }
        
        public ProudSourcePrime.ServiceReference1.ProjectIndexComposite get_ProjectIndexData(string UserId, int entrepreneur_id, int project_id) {
            return base.Channel.get_ProjectIndexData(UserId, entrepreneur_id, project_id);
        }
        
        public ProudSourcePrime.ServiceReference1.ProjectDetailsComposite get_ProjectDetails_Data(int Project_Id) {
            return base.Channel.get_ProjectDetails_Data(Project_Id);
        }
        
        public bool update_ProjectProfileData(string UserId, int Entrepreneur_Id, int Project_Id, System.Collections.Generic.Dictionary<string, string> projectdata) {
            return base.Channel.update_ProjectProfileData(UserId, Entrepreneur_Id, Project_Id, projectdata);
        }
        
        public int create_PROC(string UserId, int Investor_Id, int Project_Id, System.Collections.Generic.Dictionary<string, string> PROCdata) {
            return base.Channel.create_PROC(UserId, Investor_Id, Project_Id, PROCdata);
        }
        
        public ProudSourcePrime.ServiceReference1.PROCComposite get_PROC(int proc_id, int entrepreneur_id, int investor_id) {
            return base.Channel.get_PROC(proc_id, entrepreneur_id, investor_id);
        }
        
        public bool update_PROC(int proc_id, System.Collections.Generic.Dictionary<string, string> updateDictionary, int entrepreneur_id, int investor_id) {
            return base.Channel.update_PROC(proc_id, updateDictionary, entrepreneur_id, investor_id);
        }
        
        public bool alter_PROC_MutualyAccepted(int proc_id, bool investor_mutualy_accepts_PROC, int entrepreneur_id, int investor_id) {
            return base.Channel.alter_PROC_MutualyAccepted(proc_id, investor_mutualy_accepts_PROC, entrepreneur_id, investor_id);
        }
        
        public bool recant_PROC_MutualAcceptance(int proc_id, bool mutual_acceptance, int entrepreneur_id, int investor_id) {
            return base.Channel.recant_PROC_MutualAcceptance(proc_id, mutual_acceptance, entrepreneur_id, investor_id);
        }
        
        public bool upload_Link(System.Collections.Generic.Dictionary<string, string> link) {
            return base.Channel.upload_Link(link);
        }
        
        public bool delete_Link(int link_id, int profile_id, int profile_type_id) {
            return base.Channel.delete_Link(link_id, profile_id, profile_type_id);
        }
        
        public ProudSourcePrime.ServiceReference1.FinancialAccountComposite get_FinancialAccountData(string UserId, int account_id) {
            return base.Channel.get_FinancialAccountData(UserId, account_id);
        }
        
        public bool create_new_BT_Transactions(string UserId, int account_Id, string nonce, decimal amount) {
            return base.Channel.create_new_BT_Transactions(UserId, account_Id, nonce, amount);
        }
        
        public System.Collections.Generic.Dictionary<string, string>[] ajax_SearchResults(string keyArg) {
            return base.Channel.ajax_SearchResults(keyArg);
        }
    }
}
